providers = ["node"]

[variables]
TZ = "America/Bogota"
LANG = "C.UTF-8"
LC_ALL = "C.UTF-8"

[phases.setup]
nixPkgs = ["tzdata"]

[phases.build]
cmds = ["npm ci", "npm run build"]

[start]
cmd = "npx serve -s dist -l $PORT"
